# Playbook for building and deploying a Docker container
- name: Build & Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Copy the files to remote server
      # Task to copy the necessary files from the Jenkins workspace to the remote server
      become: true
      copy:
        src: /var/lib/jenkins/workspace/ansible-jenkins-pipeline/
        dest: ~/project

    - name: Building Docker Image
      # Task to build the Docker image using the files copied to the remote server
      docker_image:
        build:
          path: ~/project
        name: hostit:latest
        source: build
        state: present
    
    - name: Stopping the Container
      # Task to stop the currently running container (if any)
      docker_container:
        name: hostit-container
        image: hostit:latest
        state: stopped

    - name: Remove the Container
      # Task to remove the existing container (if any)
      docker_container:
        name: hostit-container
        image: hostit:latest
        state: absent
  
    - name: Removing Docker Image
      # Task to remove the Docker image from the host
      docker_image:
        name: hostit:latest
        state: absent

    - name: Building Docker Image
      # Task to build the Docker image again (after removal) to ensure latest changes are incorporated
      docker_image:
        build:
          path: ~/project
        name: hostit:latest
        source: build
        state: present

    - name: Creating the Container
      # Task to create and start the Docker container with port mapping (host port 80 to container port 80)
      docker_container:
        name: hostit-container
        image: hostit:latest
        ports:
          - "80:80"
        state: started